stages:
  #- assemble
  - copy

image: openmole/build

assemble:
  stage: assemble
  script:
    - bash -x build.sh
    - '(cd openmole && ./generateSite ./site)'
  cache:
    paths:
      - ./openmole/site # répertoire mis en cache
    policy: push # le cache sera juste sauvegardé, pas de récupération d'un cache existant


copy:
  stage: copy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "put -r ./openmole/build.sbt next" >tonext
    - sftp -P 21022 user@docker.openmole.org -b tonext 
  cache:
    paths:
      - ./openmole/site # répertoire mis en cache
    policy: pull # le cache sera juste sauvegardé, pas de récupération d'un cache existant
   



