stages:
  - assemble
  - copy

image: openmole/build

assemble:
  stage: assemble
  script:
    - bash -x build.sh
    - '(cd openmole && ./generateSite ./site)'
  cache:
    paths:
      - ./openmole/site # répertoire mis en cache
    policy: push # le cache sera juste sauvegardé, pas de récupération d'un cache existant


copy:
  stage: copy
  before_script:
    #- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    #- eval $(ssh-agent -s)
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #- echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_PRIVATE_KEY" >~/.ssh/identity
    - chmod 400 ~/.ssh/identity
    - ssh-keyscan -p 21022 docker.openmole.org > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "put -r ./site/* next" >./tonext
    - sftp -i ~/.ssh/identity -b ./tonext -P 21022 user@docker.openmole.org
  cache:
    paths:
      - ./openmole/site # répertoire mis en cache
    policy: pull # le cache sera juste sauvegardé, pas de récupération d'un cache existant
  variables:
    GIT_STRATEGY: none
   



