stages:
  - assemble
  - deploy

image: openmole/build

assemble:
  stage: assemble
  script:
    - rm -f openmole/.sbtopts
    - bash -x build.sh
    - '(cd openmole && sbt test)'
    - '(cd openmole && ./generateSite $PWD/site)'
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - openmole/

copy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >~/.ssh/identity
    - chmod 400 ~/.ssh/identity
    - ssh-keyscan -p 21022 docker.openmole.org > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "put -r ./openmole/site/* next" >./tonext
    - sftp -i ~/.ssh/identity -b ./tonext -P 21022 user@docker.openmole.org
  variables:
    GIT_STRATEGY: none
  cache:
    key: ${CI_COMMIT_REF_SLUG}
   



