image: openmole/openmole-buildenv

variables:
  HOME: "$CI_PROJECT_DIR"
  IVY_HOME: "$HOME/.ivy2"
  SBT_OPTS: "-Dsbt.ivy.home=$IVY_HOME"

before_script:
  - apt update
cache:
  untracked: true

build_site:
  script:
    - (cd build-system && sbt clean publishLocal)
    - (cd libraries && sbt clean publishLocal)
    - (cd openmole && sbt clean)
    - (cd openmole && ./generateSite $WORKSPACE/openmole/bin/target/site/)

