stages:
  - assemble
  - copy

image: openmole/build

assemble:
  stage: assemble
  script:
    - echo youpi
    #- bash -x build.sh
    #- '(cd openmole && ./generateSite ./site)'
  cache:
    paths:
      - ./openmole/site # répertoire mis en cache
    policy: push # le cache sera juste sauvegardé, pas de récupération d'un cache existant


copy:
  stage: copy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "put -r ./openmole/build.sbt next" >./tonext
    - cat tonext
    - sftp -b ./tonext -P 21022 user@docker.openmole.org
  cache:
    paths:
      - ./openmole/site # répertoire mis en cache
    policy: pull # le cache sera juste sauvegardé, pas de récupération d'un cache existant
  #variables:
  #  GIT_STRATEGY: none
   



