stages:
  - assemble
  - deploy

image: openmole/build

assemble:
  stage: assemble
  script:
    - bash -x build.sh
    - '(cd openmole && ./generateSite $PWD/site)'
  cache:
    paths:
      - ./openmole
      - /root/.ivy2/
    policy: push

test:
  stage: deploy
  script:
    - '(cd openmole && sbt test)'
  cache:
    paths:
      - ./openmole
      - /root/.ivy2/
    policy: pull 
  variables:
    GIT_STRATEGY: none

copy:
  stage: deploy
  before_script:
    #- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    #- eval $(ssh-agent -s)
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #- echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_PRIVATE_KEY" >~/.ssh/identity
    - chmod 400 ~/.ssh/identity
    - ssh-keyscan -p 21022 docker.openmole.org > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "put -r ./openmole/site/* next" >./tonext
    - sftp -i ~/.ssh/identity -b ./tonext -P 21022 user@docker.openmole.org
  cache:
    paths:
      - ./openmole
    policy: pull
  variables:
    GIT_STRATEGY: none
   



